# Generated by Django 5.2 on 2025-04-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Audio', 'Audio'), ('Gaming', 'Gaming'), ('Fitness', 'Fitness'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Kitchen', 'Kitchen'), ('Books', 'Books'), ('Accessories', 'Accessories')], max_length=50)),
                ('price', models.FloatField()),
            ],
        ),
    ]
